AzureDiagnostics
| where OperationName == "Microsoft.Cdn/Profiles/AccessLog/Write"
| where $__timeFilter(TimeGenerated)
| extend originName_s=replace_regex(originName_s, @"^(.+).z[0-9]{1,2}\.web\.core\.windows\.net:443$", @"\1")
| extend originName_s=replace_regex(originName_s, @"^(.+).cloudapp.azure.com:443$", @"\1")
| summarize Requests=count() by bin(TimeGenerated, 2m), Backend=originName_s
| order by TimeGenerated asc