WebsiteHealthScore
| union AddGameResultUserFlowHealthScore
| union GetPlayerStatsUserFlowHealthScore
| union ShowStaticContentUserFlowHealthScore
| union PublicBlobStorageHealthScore
| union KeyvaultHealthScore
| union GameServiceHealthScore
| union CheckpointStorageHealthScore
| union ResultWorkerHealthScore
| union ClusterHealthScore
| summarize arg_max(TimeGenerated, *) by ComponentName,Dependencies
| project-away TimeGenerated