WebsiteHealthScore
| union AddCommentUserFlowHealthScore
| union ListCatalogItemsUserFlowHealthScore
| union ShowStaticContentUserFlowHealthScore
| union PublicBlobStorageHealthScore
| union KeyvaultHealthScore
| union CatalogServiceHealthScore
| union EventHubHealthScore
| union CheckpointStorageHealthScore
| union BackgroundProcessorHealthScore
| union ClusterHealthScore
| summarize arg_max(TimeGenerated, *) by ComponentName,Dependencies
| project-away TimeGenerated