(PublicBlobStorageHealthStatus | extend ComponentName="PublicBlobStorage")
| union (KeyvaultHealthStatus | extend ComponentName="Keyvault")
| union (GameServiceHealthStatus | extend ComponentName="GameService")
| union (ResultWorkerHealthStatus | extend ComponentName="ResultWorker")
| union (ClusterHealthStatus | extend ComponentName="Cluster")
| where $__timeFilter(TimeGenerated)
| where IsYellow > 0 or IsRed > 0
| extend Status=iif(IsRed == 1 ,'red', 'yellow')
| project TimeStamp=TimeGenerated, ['Component Name']=ComponentName, Metric=MetricName, Value, Status
| order by TimeStamp desc