// Returns the health score for the 'loadwebsite' user flow
// This is the _lowest_ value of the PublicBlobStorage component
PublicBlobStorageHealthStatus
| where TimeGenerated < ago(2m)
| summarize YellowScore = max(IsYellow), RedScore = max(IsRed) by bin(TimeGenerated, 2m)
| extend HealthScore = 1 - (YellowScore * 0.25) - (RedScore * 0.5)
| order by TimeGenerated desc
| extend ComponentName = "ShowStaticContentUserFlow", Dependencies = "PublicBlobStorage"
