# Variable file for E2E env
cosmosdb_collection_catalogitems_max_autoscale_throughputunits = 4000
cosmosdb_collection_itemcomments_max_autoscale_throughputunits = 4000
cosmosdb_collection_itemratings_max_autoscale_throughputunits  = 4000
